// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUjiJ6s-FztpPLohFXtKm6_MYa83xhGkg',
    appId: '1:240289797566:web:c16e746ccc9fcaff5455ef',
    messagingSenderId: '240289797566',
    projectId: 'mughtarib-feb40',
    authDomain: 'mughtarib-feb40.firebaseapp.com',
    storageBucket: 'mughtarib-feb40.firebasestorage.app',
    measurementId: 'G-40J2VH6Y6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2HqNnsJCx9pcGAVUi_CB6b5nZYIg49cE',
    appId: '1:240289797566:android:75512fdf6a6a69ae5455ef',
    messagingSenderId: '240289797566',
    projectId: 'mughtarib-feb40',
    storageBucket: 'mughtarib-feb40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0CFj6qpbgwAOHwwdMvVLXTSfcRaSyJ1A',
    appId: '1:240289797566:ios:0cd5ec5987c32e555455ef',
    messagingSenderId: '240289797566',
    projectId: 'mughtarib-feb40',
    storageBucket: 'mughtarib-feb40.firebasestorage.app',
    iosClientId: '240289797566-k9a362icn3ukebni0vhtp4a3f5beu84f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mughtaribApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0CFj6qpbgwAOHwwdMvVLXTSfcRaSyJ1A',
    appId: '1:240289797566:ios:0cd5ec5987c32e555455ef',
    messagingSenderId: '240289797566',
    projectId: 'mughtarib-feb40',
    storageBucket: 'mughtarib-feb40.firebasestorage.app',
    iosClientId: '240289797566-k9a362icn3ukebni0vhtp4a3f5beu84f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mughtaribApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUjiJ6s-FztpPLohFXtKm6_MYa83xhGkg',
    appId: '1:240289797566:web:22a5787552e3a9875455ef',
    messagingSenderId: '240289797566',
    projectId: 'mughtarib-feb40',
    authDomain: 'mughtarib-feb40.firebaseapp.com',
    storageBucket: 'mughtarib-feb40.firebasestorage.app',
    measurementId: 'G-9RGVKLB4CF',
  );
}
